- route:
    id: route-3885
    description: Get request every 5s
    from:
      id: from-4847
      uri: timer:t
      parameters:
        period: 5000
      steps:
        - setHeader:
            id: setHeader-1867
            expression:
              constant:
                expression: "12345"
            name: customerId
        - to:
            id: to-4437
            uri: rest-openapi:api-registry/${{ values.apis[0].split('/')[1]}}-api.json#operationIdUpdateMe
            parameters:
              basePath: /api/v1
              host: https://${{ values.apis[0].split('/')[1]}}-${{ values.application.split("/")[1] }}-dev.apps.cluster.com
        - log:
            id: log-3873
            message: ${body}
